#!/bin/bash

# Install WordPress.

DOTENV=".env"
WP="lando wp"

# Source dot env vars.
set -a; source $DOTENV; set +a;

$WP core download --force

$WP config create \
    --dbname=$TW_DBNAME \
    --dbuser=$TW_DBUSER \
    --dbpass=$TW_DBPASS \
    --dbhost=$TW_DBHOST \
    --force

$WP config set DB_NAME "getenv( 'TW_DBNAME' )" --raw
$WP config set DB_USER "getenv( 'TW_DBUSER' )" --raw
$WP config set DB_PASSWORD "getenv( 'TW_DBPASS' )" --raw
$WP config set DB_HOST "getenv( 'TW_DBHOST' )" --raw

$WP config set TW_ENV $TW_ENV

DEBUG_DISPLAY=true
if [ 'prod' == $TW_ENV ]; then
    DEBUG_DISPLAY=false
fi

$WP config set WP_DEBUG true --raw
$WP config set WP_DEBUG_LOG $DEBUG_DISPLAY --raw
$WP config set WP_DEBUG_DISPLAY true --raw

sed -i "s/<?php/<?php\n\nrequire_once dirname( __FILE__, 2 ) . '\/secrets.php';\n/g" ./htdocs/wp-config.php

$WP core install \
    --url=$TW_URL \
    --title="Tom Weights" \
    --admin_user=$TW_ADMIN \
    --admin_password=$TW_PASS \
    --admin_email=$TW_EMAIL \
    --skip-email

$WP plugin delete akismet hello
$WP theme delete twentytwentyone twentytwentytwo

$WP plugin install simply-static